Tg 18
project-salsa/player-finder pull request #8
Opened 2017-10-11 03:37 UTC by DanFuchs96

This branch has the basic login page and first time component (rebuilt in nativebase and standard styled)

2017-10-17 19:38 UTC, renodubois requested changes
Sorry for the delay, here's my initial pass on this.

Let me know if you have questions!

2017-10-17 19:38 UTC, renodubois commented on components/first_time/first_time_component.js
> +              <Input onChangeText={(input) => this.setState({field1: input})} />
I would make a function named `handleInput` or similar so that you're not repeating the same code for every input field.

React's docs have a good rundown on that: https://reactjs.org/docs/forms.html#handling-multiple-inputs

2017-10-17 19:38 UTC, renodubois commented on components/first_time/first_time_component.js
> +                alert("I'll do HTTP stuff soon")
Same with this, a `handleSubmit` function is more standard practice.

2017-10-17 19:38 UTC, renodubois commented on components/first_time/first_time_component.js
> +      field1: undefined,
Making these empty strings seems more straightforward to me, as they indicate what type the variable is expected to be. Honestly, its a pretty small change, and you might have a reason for making it undefined that I'm not aware of, so definitely push back if you need to.

2017-10-17 19:38 UTC, renodubois commented on components/login/login_component.js
> +              <Input onChangeText={(input) => this.setState({username: input})} />
Refer to the above comment regarding changing input.

2017-10-18 00:49 UTC, DanFuchs96 commented on components/first_time/first_time_component.js
> +                alert("I'll do HTTP stuff soon")
but should I really define a function that i'll use exactly one time? wouldn't that just clutter up the code?

2017-10-18 01:26 UTC, closed without merging